# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 852133af7ddbac6b3759fb2bd3e1fe6e31c6f3c081ae32feba9c89ab977fb2e9ef420b4fdcfbf779745e53d4ac909fb6604dbb0b3a8b693101559a97a1a4b6a0

test:
  secret_key_base: 28be1796c945e14e75c57be3544fd67e3507a46d54994794149f5f4e3891cb76ac4ee70be78d93f96e04f02c501c6af5ae4778c12b2bc066f34af5a3ac5b833c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
